services:
  dearnextvisitor:
    image: nginx:latest # TODO
    secrets:
      - openai_api_key
    networks:
      - dnv-network
      - web-network
    environment:
      NEXT_PUBLIC_POSTHOG_KEY: phc_S8wR0LhS6z30om4UBirN1wpOc5jyrBALur4Apdw8HJ5
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      VALKEY_URL: valkey://valkey:6379
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  valkey:
    image: valkey/valkey:8.1.3
    volumes:
      - /mnt/HC_Volume_102954257/apps/dearnextvisitor/data/valkey:/data
    networks:
      - dnv-network
    command: >
      valkey-server
      --appendonly yes
      --appendfsync always
      --dir /data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.name == node01
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

secrets:
  openai_api_key:
    name: dnv_openai_api_key
    external: true

networks:
  dnv-network:
    driver: overlay
    attachable: true
  web-network:
    name: web-stack_web-network
    external: true
