/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DnvWeb": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "LIBSQL_DB_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LIBSQL_DB_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}