import type { Metadata } from "next";
import { bodyFont, handFont } from '@/fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`bg-zinc-700 ${handFont.variable} ${bodyFont.variable}`}>
      <body>{children}</body>
    </html>
  );
}
